# Generated by Django 4.1.2 on 2024-12-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2000)),
                ("singer", models.CharField(max_length=2000)),
                ("tags", models.CharField(max_length=100)),
                ("image", models.FileField(upload_to="images")),
                ("song1", models.FileField(upload_to="images")),
            ],
        ),
    ]
