# Generated by Django 4.1.2 on 2024-12-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="song", name="song1",),
        migrations.AddField(
            model_name="song",
            name="song_file",
            field=models.FileField(blank=True, null=True, upload_to="songs/"),
        ),
        migrations.AlterField(
            model_name="song",
            name="image",
            field=models.FileField(upload_to="images/"),
        ),
    ]
