# Generated by Django 4.1.2 on 2024-12-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicApp", "0002_remove_song_song1_song_song_file_alter_song_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="song", name="singer", field=models.CharField(max_length=255),
        ),
    ]
